name: Publish Artifacts

on:
  release:
    types: [released] # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Echo current actor
        run: echo 'Current user is:' $GITHUB_ACTOR

      - name: Assemble Release with Gradle
        run: ./gradlew assembleRelease
        env:
          USERNAME: ${{ env.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign build
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename file
        run: mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/zvernam.apk

      - name: Publish builded artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: app/build/zvernam.apk

      - name: Upload to release
        uses: gacts/upload-to-release@master # https://github.com/actions-github/upload-to-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: app/build/zvernam.apk
          type: application/vnd.android.package-archive

