name: Android Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Echo current actor
        run: echo 'Current user is:' $GITHUB_ACTOR

      - name: Build with Gradle
        run: ./gradlew test
        env:
          USERNAME: ${{ env.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish test result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/testReleaseUnitTest